spring.application.name=finance-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/finance_management_system
spring.datasource.username=Database Username
spring.datasource.password=Database Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8258

# Google OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id= Your Client Id
spring.security.oauth2.client.registration.google.client-secret=Your client secret
spring.security.oauth2.client.registration.google.scope=email,profile

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vedantkokare45@gmail.com
spring.mail.password=bgrrpdavvqrtsnoj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Add the Forgot Password option in the profile/setting page